version: 2
updates:
- package-ecosystem: docker
  directory: "/ops"
  schedule:
    interval: "monthly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 99
